development:
      encoding: utf8
      host: localhost
      adapter: mysql2
      database: socrates_develop
      port: 3306
      username: root
      password: 

test: &test
      encoding: utf8
      host: localhost
      adapter: mysql2
      database: socrates_test
      port: 3306
      username: root
      password:

production:
      encoding: utf8
      host: localhost
      adapter: mysql2
      database: socrates_production
      port: 3306
      username: root
      password:
